### ISSUE TITLE
how to create parsers.conf to use in fluent-bit-config secret

### ISSUE THREAD

**Issue by navneet066** [kubesphere/fluentbit-operator#102]
I am trying to add below in fluent-bit-config secret to enable the metrics as stated [here](https://docs.fluentbit.io/manual/administration/monitoring)

```yaml
[SERVICE]
    HTTP_Server  On
    HTTP_Listen  0.0.0.0
    HTTP_PORT    2020

```

But not able to do so as there is no configuration provided to add. Please let me know If I am missing anything.

In the Daemonset manifest file, there is  already a setting to access it 

```yaml
      containers:
        - name: fluent-bit
          image: 'kubespheredev/fluent-bit:v1.7.3'
          ports:
            - name: metrics
              containerPort: 2020
              protocol: TCP
```

but it is not actually exposing it.
