### ISSUE TITLE
Input resources cannot specify multiple log paths via the `path` configuration

### ISSUE THREAD

**Issue by eltonbfw** [kubesphere/fluentbit-operator#48]
It seems that multiple paths separated by commas are recognized as one path.
```yml
apiVersion: logging.kubesphere.io/v1alpha2
kind: Input
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"logging.kubesphere.io/v1alpha2","kind":"Input","metadata":{"annotations":{},"labels":{"logging.kubesphere.io/component":"logging","logging.kubesphere.io/enabled":"true"},"name":"tail","namespace":"kubesphere-logging-system"},"spec":{"tail":{"db":"/fluent-bit/tail/pos.db","dbSync":"Normal","excludePath":"/var/log/containers/*_kubesphere-logging-system_events-exporter*.log,/var/log/containers/kube-auditing-webhook*_kubesphere-logging-system_kube-auditing-webhook*.log","memBufLimit":"5MB","parser":"docker","path":"/var/log/containers/*.log","refreshIntervalSeconds":10,"skipLongLines":true,"tag":"kube.*"}}}
  labels:
    logging.kubesphere.io/component: logging
    logging.kubesphere.io/enabled: 'true'
  name: tail
  namespace: kubesphere-logging-system
spec:
  tail:
    db: /fluent-bit/tail/pos.db
    dbSync: Normal
    memBufLimit: 5MB
    parser: docker
    path: /var/log/containers/a-*.log,/var/log/containers/b-*.log
    refreshIntervalSeconds: 10
    skipLongLines: true
    tag: kube.*
```
